// type LangKey = typeof LANGS[number]["key"];
// Project type definition removed because type aliases are not supported in .jsx files.
export const projects: Project[] = [
    {
        id: "rep-mgmt-2024",
        period: "Oct 2024 – Apr 2025",
        company: "Mitsubishi Electric Software Corporation",
        title_en: "Report Management Web System (Full‑stack)",
        title_jp: "レポート管理 Web システム（フルスタック）",
        summary_en: "Built a report management system: Spring Boot backend with optimized SQL and a React (TypeScript) frontend. Designed and implemented report features, fixed bugs, and performed code reviews.",
        summary_jp: "Spring Boot を用いたサーバーサイド開発（SQL 最適化含む）と、React（TypeScript）によるフロントエンド実装。レポート管理機能の設計・実装、不具合修正、コードレビューを担当。",
        responsibilities_en: [
            "Backend development & testing with Java (Spring Boot)",
            "SQL query creation & tuning",
            "Frontend development with React (TypeScript)",
            "Report management feature design & implementation",
            "Bug fixes & code reviews",
        ],
        responsibilities_jp: [
            "Java（Spring Boot）によるバックエンド開発・テスト",
            "SQL クエリの作成・チューニング",
            "React（TypeScript）を用いたフロントエンド開発",
            "レポート管理機能の設計・実装",
            "不具合修正・コードレビュー対応",
        ],
        deliverables_en: [
            "Implemented backend & frontend for the system",
            "SQL‑based data management and search",
            "Improved reporting workflow and usability",
        ],
        deliverables_jp: [
            "システムのバックエンド・フロントエンドを実装",
            "SQL ベースのデータ管理・検索機能",
            "報告書作成・管理の効率化とユーザビリティ向上",
        ],
        stack: [
            "Java",
            "Spring Boot",
            "PostgreSQL",
            "React",
            "TypeScript",
            "Eclipse",
        ],
        team: "4 members",
        locale_note: "業務言語：日本語",
    },
    {
        id: "env-visual-2024",
        period: "Mar 2024 – Sep 2024",
        company: "Mitsubishi Electric Software Corporation",
        title_en: "Environmental Impact Visualization System (GHG for crops)",
        title_jp: "環境負荷可視化システム（作物の温室効果ガス算出）",
        summary_en: "Designed algorithms to calculate GHG emissions for tea, rice, fruit, and vegetables; migrated Excel‑based calculations to a robust web system.",
        summary_jp: "茶・米・果物・野菜などの温室効果ガス排出量算出アルゴリズムを設計・実装し、従来の Excel 計算を効率的な Web システムへ移行。",
        responsibilities_en: [
            "Python algorithm design & implementation",
            "FastAPI backend (API endpoints)",
            "ER model design & data integrity",
            "Testing with pytest; bug fixes & maintenance",
            "Team collaboration and continuous improvement",
        ],
        responsibilities_jp: [
            "Python による排出量算出アルゴリズムの設計・実装",
            "FastAPI を用いた API 開発",
            "ER モデル設計・修正、データ整合性の確保",
            "pytest によるテスト実装、バグ修正・保守",
            "チーム連携による進捗共有・改善提案",
        ],
        deliverables_en: [
            "Python‑based calculation algorithms",
            "FastAPI endpoints",
            "Improved ER model",
            "Automated tests with pytest",
        ],
        deliverables_jp: [
            "Python ベースの算出アルゴリズム",
            "FastAPI による API エンドポイント",
            "改良された ER モデル",
            "pytest を用いたテストコード",
        ],
        stack: [
            "Python",
            "FastAPI",
            "PostgreSQL",
            "SQLAlchemy",
            "Vue.js",
            "Pydantic",
            "Pytest",
            "VS Code",
            "A5:SQL Mk-2",
        ],
        team: "6 members",
        locale_note: "業務言語：日本語",
    },
    {
        id: "dna-2023",
        period: "Dec 2023 – Feb 2024",
        company: "Mitsubishi Electric Software Corporation",
        title_en: "DNA Experiment & Analysis Management System",
        title_jp: "DNA 実験・解析マネジメントシステム",
        summary_en: "Built core views with CRUD using Django; created test cases with Selenium and implemented tables with django‑datatables‑view.",
        summary_jp: "Django による CRUD 画面を作成し、Selenium でテストを作成。django‑datatables‑view を用いたテーブル画面を実装。",
        responsibilities_en: [
            "Development based on HLD/LLD",
            "CRUD views with Django",
            "UI tables with django‑datatables‑view",
            "Selenium end‑to‑end test cases",
        ],
        responsibilities_jp: [
            "基本設計書・詳細設計書に基づく開発",
            "Django による CRUD 画面作成",
            "django‑datatables‑view を用いた UI 作成",
            "Selenium によるテストケース作成",
        ],
        stack: [
            "Python",
            "Django",
            "Selenium",
            "JavaScript",
            "jQuery",
            "HTML",
            "Docker",
        ],
        team: "7 members",
        locale_note: "業務言語：日本語",
    },
    {
        id: "jaxa-2023",
        period: "Jun 2023 – Nov 2023",
        company: "Mitsubishi Electric Software Corporation (JAXA委託)",
        title_en: "Satellite Orbit Control Data Management Web App (JAXA)",
        title_jp: "衛星軌道制御データの管理 Web アプリ（JAXA 案件）",
        summary_en: "Developed a Django‑based web app to manage orbit control data; implemented server CRUD and jQuery‑based client UI using Bootstrap and DataTables.",
        summary_jp: "Django を用いて軌道制御データを管理する Web アプリを構築。サーバー側 CRUD と jQuery による UI（Bootstrap / DataTables）を実装。",
        responsibilities_en: [
            "Server: CRUD with Django models",
            "Client: jQuery UI for data operations",
            "HTML/Bootstrap mockups & templates",
            "PostgreSQL table design & SQL implementation",
        ],
        responsibilities_jp: [
            "サーバーサイド：Django によるデータ作成・登録・削除・編集",
            "クライアントサイド：jQuery による UI 開発（データ操作画面）",
            "HTML / Bootstrap / JS DataTables によるモック・テンプレート作成",
            "PostgreSQL でのテーブル設計および SQL 実装",
        ],
        stack: [
            "Python",
            "Django",
            "PostgreSQL",
            "jQuery",
            "Bootstrap",
            "JavaScript",
            "Docker",
            "VS Code",
        ],
        team: "5 members",
        locale_note: "業務言語：日本語",
    },
    {
        id: "sat-binary-2022",
        period: "May 2022 – May 2023",
        company: "Mitsubishi Electric Software Corporation",
        title_en: "Satellite Orbit Measurement: Binary Generation & Job Control",
        title_jp: "衛星軌道計測：バイナリ生成・ジョブ制御",
        summary_en: "Authored Python scripts to download data and generate complex binary files for an orbit measurement system; scripted job/command control.",
        summary_jp: "Web からデータを取得し、軌道計測システム向けの複雑なバイナリファイルを生成。ジョブ・コマンド制御用の Python スクリプトを作成。",
        stack: [
            "Python",
            "STK Python API",
            "Pydantic",
            "Windows",
            "Linux",
        ],
        team: "15 members",
        locale_note: "業務言語：日本語",
    },
    {
        id: "wpf-ai-2021",
        period: "Oct 2021 – Apr 2022",
        company: "Prostyle Technology (Sri Lanka)",
        title_en: "WPF Surveillance Alert System with AI (Fall detection, etc.)",
        title_jp: "WPF 監視カメラ警告システム（AI 連携・転倒検知など）",
        summary_en: "Developed a WPF desktop app integrating an AI module to detect human motion and abnormal behaviors; real‑time alerts to PC/mobile; multi‑camera, multiview, and playback.",
        summary_jp: "AI モジュールと連携した WPF デスクトップアプリを開発。人の動作や異常行動を検知し、PC/モバイルにリアルタイム通知。複数カメラ・マルチビュー・過去映像確認に対応。",
        responsibilities_en: [
            "UI mockups & prototypes (Moqups)",
            "Single‑camera section development",
            "HLD/LLD, test docs, SRS authoring",
            "Log simulator for testing",
        ],
        responsibilities_jp: [
            "UI モックアップ・プロトタイプ作成（Moqups）",
            "シングルカメラセクションの開発",
            "基本設計・詳細設計・テスト文書・SRS の作成",
            "テスト用ログシミュレータの作成",
        ],
        deliverables_en: [
            "WPF desktop app (real‑time alerts, multi‑camera)",
            "AI‑based motion detection integration",
            "Test log simulator",
        ],
        deliverables_jp: [
            "WPF デスクトップアプリ（リアルタイム警告・マルチカメラ）",
            "AI 連携による動作検知機能",
            "テスト用ログシミュレータ",
        ],
        stack: [
            "C#",
            "WPF",
            "Python",
            "C++",
            "HTML5",
            "JavaScript",
            "XAML",
            "LINQ",
        ],
        team: "5 members",
        locale_note: "設計〜詳細設計は日本語（日本の顧客向け）",
    },
    {
        id: "dotnet-mvc-2020",
        period: "Jun 2020 – Sep 2021",
        company: "Prostyle Technology (Sri Lanka)",
        title_en: ".NET MVC Admin Systems (Web Application)",
        title_jp: ".NET MVC 管理システム（Web アプリ）",
        summary_en: "Developed admin systems on .NET MVC with HTML5/CSS/Bootstrap UI; leveraged LINQ and MS SQL Server for efficient data access and improved UX.",
        summary_jp: ".NET MVC を基盤に管理システムを設計・実装。HTML5/CSS/Bootstrap による UI、LINQ と MS SQL Server による効率的なデータ操作を実施。",
        stack: [
            "C# .NET (MVC)",
            "HTML5",
            "CSS",
            "Bootstrap",
            "LINQ",
            "MS SQL Server",
            "Ajax",
            "Razor",
            "jQuery",
        ],
        team: "5 members",
        locale_note: "設計〜詳細設計は日本語（日本の顧客向け）",
    },
    {
        id: "labvantage-lims",
        period: "(Ongoing @ MESW)",
        company: "Mitsubishi Electric Software Corporation",
        title_en: "LabVantage LIMS: Functional Testing & Bug Fixes",
        title_jp: "LabVantage LIMS：機能テスト・不具合修正",
        summary_en: "Performed functional testing, bug fixes, and code reviews to improve quality. Delivered customized LabVantage modules incl. Excel export; stabilized and extended LIMS features.",
        summary_jp: "機能テスト・不具合修正・コードレビューを実施し品質を向上。Excel 出力対応を含むカスタマイズ済み LabVantage モジュールを提供し、LIMS の機能拡張・安定化を実現。",
        stack: ["LabVantage", "LIMS", "Excel"],
    },
];
